---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86175.
--- DateTime: 2021/10/22 15:52
---

local _M = {arg = 0}
_M.__index = _M

function _M:new (o,opts)
    if _M ~= self then
        print("Fatal Error!")
    end
    local o = o or {}
    setmetatable(o, self)
    self.arg = opts.arg
    return o
end

-- 深克隆
function _M:clone ()
    return self
end

function _M:print()
    print("Hello"..self.arg)
end


return _M