---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86175.
--- DateTime: 2021/10/22 16:36
---

-- 演示元表的作用

local thd = {key = "thd-value"}
local fst = {}
local snd = {key = "snd-value", snd="snd", __index = thd }
setmetatable(fst,snd)

print(fst.snd) -- nil
print(fst.key) -- thd-value

-- 如果设置了fst的元表，并且元表的设置了__index的值为一个表！
-- 那么在fst查找某个key时，如果key不存在，并不会在元表(snd)中查找(即使元表中存在这个key(例如:key、snd))
-- 而是会在元表中的__index所指的表(thd)中去查找是否有这个key！