---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86175.
--- DateTime: 2021/10/22 15:46
---

print(_VERSION)
for  key, value in pairs(_G) do
    print(key.."\t"..type(value))
end

