---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86175.
--- DateTime: 2021/10/26 22:33
---

local function Split(plainText, separator)
    local startIndex = 1
    local splitIndex = 1
    local splitTable = {}
    while true do
        local lastIndex = string.find(plainText, separator, startIndex)
        if not lastIndex then
            splitTable[splitIndex] = string.sub(plainText, startIndex, string.len(plainText))
            break
        end
        splitTable[splitIndex] = string.sub(plainText, startIndex, lastIndex - 1)
        startIndex = lastIndex + string.len(separator)
        splitIndex = splitIndex + 1
    end
    return splitTable
end



local list = Split("/abc/123/345/32432", "/")
for key,val in pairs(list) do
    print("key:"..key.."\t".."value:"..val)
end
print(list[#list])