---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86175.
--- DateTime: 2021/11/19 9:49
---


local function urlSafeBase64Decode(base64Str)

    -- local safeStr = base64Str.replace(/-/g, '+').replace(/_/g, '/');

    --local safeStr = string.gsub(base64Str, "-", "+")
    --safeStr = string.gsub(base64Str, "_", "/")
    --
    --local num = safeStr.length % 4;
    --return (safeStr .. "====").substring(0, num);

end

local result,error =  cjson.decode("fda")
print(error)


